[pytest]
addopts = -p no:pytest_asyncio --ignore=modules/inferencing/lib_tflite_micro/lib_tflite_micro/submodules/ruy/third_party/googletest/googlemock/test/gmock-function-mocker_nc_test.py
markers =
    hil: hardware-in-the-loop tests that require connected devices
    sat1: tests specific to Satellite1 board bring-up and integration
    sq66: tests specific to XK-VOICE-SQ66 board bring-up and integration
