#pragma once

#include <stdint.h>

#ifndef appconfAUDIO_PIPELINE_DEBUG_SNAPSHOTS
#define appconfAUDIO_PIPELINE_DEBUG_SNAPSHOTS 0
#endif

enum e_audio_pipeline_settings_cmds
{
    AUDIO_PIPELINE_SETTINGS_CMD_GET_SETTINGS = 0,
    AUDIO_PIPELINE_SETTINGS_CMD_SET_SETTINGS_PARTIAL,
    AUDIO_PIPELINE_SETTINGS_CMD_GET_AVAILABLE_MIC_COUNT,
    AUDIO_PIPELINE_SETTINGS_CMD_GET_DOA_RAW,
    AUDIO_PIPELINE_SETTINGS_CMD_GET_DOA_SMOOTH,
    AUDIO_PIPELINE_SETTINGS_CMD_GET_MIC_INPUT_DEBUG_STATS,
#if appconfAUDIO_PIPELINE_DEBUG_SNAPSHOTS
    AUDIO_PIPELINE_SETTINGS_CMD_GET_MIC_INPUT_PACKAGED_SNAPSHOT,
    AUDIO_PIPELINE_SETTINGS_CMD_GET_SPK_INPUT_PACKAGED_SNAPSHOT,
    AUDIO_PIPELINE_SETTINGS_CMD_GET_MIC_OUTPUT_PACKAGED_SNAPSHOT,
#endif

    NUM_AUDIO_PIPELINE_SETTINGS_CMDS
};

typedef enum
{
    AUDIO_PIPELINE_SETTINGS_MIC_GAIN_FIELD = (1u << 0),
    AUDIO_PIPELINE_SETTINGS_REF_GAIN_FIELD = (1u << 1),
    AUDIO_PIPELINE_SETTINGS_PACK_EXTRA_UPSAMPLE_CHANNELS_FIELD = (1u << 2),
    AUDIO_PIPELINE_SETTINGS_I2S_CHANNEL_MAP_FIELD = (1u << 3),
    AUDIO_PIPELINE_SETTINGS_UPSAMPLE_CHANNEL_MAP_FIELD = (1u << 4),
    AUDIO_PIPELINE_SETTINGS_REF_SOURCE_MODE_FIELD = (1u << 5),
    AUDIO_PIPELINE_SETTINGS_MIC_SOURCE_MODE_FIELD = (1u << 6),
    AUDIO_PIPELINE_SETTINGS_REF_INPUT_CHANNEL_MAP_FIELD = (1u << 7),
    AUDIO_PIPELINE_SETTINGS_MIC_INPUT_CHANNEL_MAP_FIELD = (1u << 8),
    AUDIO_PIPELINE_SETTINGS_OVERWRITE_REF_WITH_IC_NS_OUTPUT_FIELD = (1u << 9),
} audio_pipeline_mic_settings_field_mask_t;

typedef enum
{
    AUDIO_PIPELINE_SETTINGS_SPK_EQ_ENABLED_FIELD = (1u << 0),
    AUDIO_PIPELINE_SETTINGS_SPK_EQ_PROFILE_ID_FIELD = (1u << 1),
} audio_pipeline_speaker_settings_field_mask_t;
